name: Manual Greeting

on:
    workflow_dispatch:
        inputs:
            greeting:
                type: string
                default: 'hello'
                required: true
                description: A cheerful greeting message

jobs:
    greet:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{ inputs.greeting }}"